---
# tasks file for hw_role_apache
- name: install apache2
  apt: name=apache2 update_cache=yes state=latest
  
- name: Insert Index Page
  template:
    src: files/index.html
    dest: /var/www/html/index.html