---
# tasks file for hw_role
- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Insert Index Page
  template:
    src: files/index.html
    dest: /usr/share/nginx/html/index.html

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present
